### ISSUE TITLE
Feature request: PDF Upload

### ISSUE THREAD

**Issue by robertharm** [BRZ-GmbH/CovidCertificate-App-Android#3]
Hab die App an Bekannte weiterempfohlen und bei 2 von 3 bekam ich die Rückmeldung "da kann ich ja mein PDF nicht uploaden". Es wäre im Hinblick auf die Usability (und für Personen, die zB kein 2. Gerät oder keinen Drucker haben), hilfreich, eine entsprechende Upload-Funktion auch in der App direkt anzubieten.

**Comment by thgoebel** [comment]
Sie können über das "Teilen"-Menü Ihres PDF-Viewers oder Dateimanagers ein PDF an die App schicken.

Ein Button direkt in der App hat die Schweizer App zwischenzeitlich auch, es würde mich nicht überraschen wenn dies hier auch bald nachgezogen wird.

**Comment by robertharm** [comment]
Danke für den Hinweis! Wenn dieser Button nicht in der App eingebaut wird, wäre es sicher hilfreich, diese Info auch in der App hinzuzufügen, darauf wäre ich nicht gekommen...

**Comment by jondo** [comment]
Die alternative App der FH-Oberösterreich-Studierenden ([github](https://github.com/GreenPassApp/greenpass-app/), [webpage](https://greenpassapp.eu/)) kann auch PDF-Upload.

**Comment by robertharm** [comment]
Gerade auf https://www.derstandard.at/story/2000127987031/gruener-pass-die-app-ist-endlich-da-die-kritik-will gelesen:

"Seit Mittwochmorgen gibt es eine neue Version der App für iOS, in der es jetzt einen neuen Knopf gibt, über den die Importfunktion erreicht werden kann. Ein entsprechendes Update für Android-Geräte wurde ebenfalls bereits an Google geschickt und soll in Kürze auch den Usern zur Verfügung stehen."
